const CHECK_TABLE_EXIST = `SELECT name
  FROM sqlite_master
  WHERE type='table' and name=?;`;

const CREATE_TABLE_CATEGORIES = `CREATE TABLE IF NOT EXISTS CATEGORIES (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);`
const CREATE_TABLE_QUIZ = `CREATE TABLE IF NOT EXISTS QUIZ (id INTEGER PRIMARY KEY AUTOINCREMENT, fk_category INTEGER, FOREIGN KEY(fk_category) REFERENCES CATEGORIES(id));`
const CREATE_TABLE_ANSWERS = `CREATE TABLE IF NOT EXISTS ANSWERS (id INTEGER PRIMARY KEY AUTOINCREMENT, answer TEXT, isCorrect BOOLEAN, fk_quiz INTEGER, FOREIGN KEY(fk_quiz) REFERENCES QUIZs(id));`
const GET_CATEGORIES = `SELECT * FROM CATEGORIES`;

export { CHECK_TABLE_EXIST, CREATE_TABLE_CATEGORIES, CREATE_TABLE_QUIZ, CREATE_TABLE_ANSWERS, GET_CATEGORIES }